spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    #MVCC => 그나마 여러개가 한번에 접근할때 빠르게 권장
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #데이터 베이스 설정 완료

  jpa:
    hibernate:
      ddl-auto: create #엔티티 정보보고 다시 만들어주는 것
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # 로그를 통해서 찍게 도와줌
  # org.hibernate.type:  trace

#이렇게까지 하며 기본설정 끝